version: '3.5'
services:
    dashboardapi:
        container_name: dashboardapi
        build:
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - './api:/usr/src/api'
            - /usr/src/api/node_modules
        ports:
            - '8080:8080'
        links:
            - mongo
        depends_on:
            - mongo
        environment:
            - NODE_ENV=development
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./mongodb/data:/data/db
        ports:
            - '27017:27017'